services:
  source-postgres:
    container_name: source-postgres
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=$SOURCE_POSTGRES_USER
      - POSTGRES_PASSWORD=$SOURCE_POSTGRES_PASSWORD
      - POSTGRES_DB=$SOURCE_POSTGRES_DBNAME
    volumes:
      - $SOURCE_POSTGRES_VOLUME:/var/lib/postgresql/data
    ports:
      - $SOURCE_POSTGRES_HOST:$SOURCE_POSTGRES_PORT:5432
    healthcheck:
      test: pg_isready -U ${SOURCE_POSTGRES_USER} -d ${SOURCE_POSTGRES_DBNAME}
      interval: 10s
      timeout: 5s
      retries: 5
